# kafka
spring:
  kafka:
    bootstrap-servers: ds1:9092
    consumer:
      group-id: peekPro
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    dynamic:
      master:
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://estest:3306/alpha_market?useUnicode=true&amp;characterEncoding=utf8mb4;autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull&amp;allowMultiQueries=true

logging:
  level:
    com.icourt.*: DEBUG
#    org:
#      docx4j:
#        convert:
#          out:
#            common:
#              writer:
#                AbstractMessageWriter: error
#    root: ERROR

#      slave:
#        one:
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.jdbc.Driver
#          url: jdbc:mysql://47.100.20.186:3308/dynamic?characterEncoding=utf8&useSSL=false
#        two:
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.jdbc.Driver
#          url: jdbc:mysql://47.100.20.186:3309/dynamic?characterEncoding=utf8&useSSL=false